"""Shared residential DSM claim labels and thermostat bounds."""

CLAIM_MODEL = "HYPOTHETICAL_GL14_TUNED_DEMO_MODEL"
CLAIM_ASSUMPTIONS = "ILLUSTRATIVE_RESIDENTIAL_ASSUMPTIONS"
CLAIM_TARIFF = "ILLUSTRATIVE_HIGH_VALUE_TOU_TARIFF"
INTERVALS_PER_DAY = 288
DT_HOURS = 1 / 12
DEFAULT_HEAT_F = 71.5
DEFAULT_COOL_F = 72.5
MAX_HEAT_F = 69.5
MAX_COOL_F = 74.5
CENTER_F = 72.0
