"""Shared residential DSM claim labels and thermostat bounds."""

CLAIM_MODEL = "HYPOTHETICAL_GL14_TUNED_DEMO_MODEL"
CLAIM_ASSUMPTIONS = "ILLUSTRATIVE_RESIDENTIAL_ASSUMPTIONS"
CLAIM_TARIFF = "ILLUSTRATIVE_HIGH_VALUE_TOU_TARIFF"
INTERVALS_PER_DAY = 288
DT_HOURS = 1 / 12
DEFAULT_HEAT_F = 71.5
DEFAULT_COOL_F = 72.5
MAX_HEAT_F = 69.5
MAX_COOL_F = 74.5
CENTER_F = 72.0

# Demo calendar days (Golden/NREL TMY3). Jan 15 is mild/typical; Jan 3 is near-design cold.
SUMMER_DEMO_MONTH = 7
SUMMER_DEMO_DAY = 15
WINTER_DESIGN_MONTH = 1
WINTER_DESIGN_DAY = 3
WINTER_TYPICAL_MONTH = 1
WINTER_TYPICAL_DAY = 15

# Summer DR aligned to illustrative TOU peak band (16-21 at $0.55/kWh).
SUMMER_DR_PRE_START_HOUR = 13.0
SUMMER_DR_EVENT_START = 15.0
SUMMER_DR_EVENT_END = 20.0
SUMMER_DR_RECOVER_END = 23.0
SUMMER_TOU_PEAK_START = 16.0
SUMMER_TOU_PEAK_END = 21.0
