---
# Per-host inventory — see inventory.example.yml

all:
  children:
    pi_bcn:
      hosts:
        bacnet_pi:
          ansible_host: 192.168.204.12
          ansible_user: ben

        acme_vm_bbartling:
          ansible_host: 100.122.106.124
          ansible_user: bbartling
