server {
    listen 80;
    root /usr/share/nginx/html;
    include /etc/nginx/mime.types;

    location /app8/ {
        try_files $uri $uri/ /app8/index.html;
    }

    location = / {
        return 302 /app8/;
    }
}
