#!/usr/bin/env bash
# Render /etc/caddy/bas-lite.caddy from /etc/default/caddy-bas-lite
# Usage: sudo ./render-caddyfile.sh [env_file] [output_file]

set -euo pipefail

ENV_FILE="${1:-/etc/default/caddy-bas-lite}"
OUT_FILE="${2:-/etc/caddy/bas-lite.caddy}"

if [[ ! -f "$ENV_FILE" ]]; then
  echo "Missing env file: $ENV_FILE" >&2
  exit 1
fi

# shellcheck disable=SC1090
set -a
source "$ENV_FILE"
set +a

UPSTREAM="${CADDY_UPSTREAM:-127.0.0.1:8080}"
PREFIX="${CADDY_APP_PREFIX:-/app8}"
PREFIX="${PREFIX%/}"
[[ "$PREFIX" == /* ]] || PREFIX="/${PREFIX}"

TLS_ENABLE="${CADDY_TLS_ENABLE:-0}"
AUTH_ENABLE="${CADDY_BASIC_AUTH_ENABLE:-0}"
TLS_CERT="${CADDY_TLS_CERT:-/etc/caddy/ssl/bas-lite.crt}"
TLS_KEY="${CADDY_TLS_KEY:-/etc/caddy/ssl/bas-lite.key}"

write_common_block() {
  local fd="$1"
  if [[ "$AUTH_ENABLE" == "1" || "$AUTH_ENABLE" == "true" || "$AUTH_ENABLE" == "yes" ]]; then
    if [[ -z "${CADDY_BASIC_AUTH_USER:-}" || -z "${CADDY_BASIC_AUTH_HASH:-}" ]]; then
      echo "CADDY_BASIC_AUTH_ENABLE is on but CADDY_BASIC_AUTH_USER or CADDY_BASIC_AUTH_HASH is empty." >&2
      exit 1
    fi
    printf '\tbasic_auth /* {\n\t\t' >&"$fd"
    printf '%s' "$CADDY_BASIC_AUTH_USER" >&"$fd"
    printf ' ' >&"$fd"
    printf '%s' "$CADDY_BASIC_AUTH_HASH" >&"$fd"
    printf '\n\t}\n' >&"$fd"
  fi
  printf '\t@root path /\n' >&"$fd"
  printf '\tredir @root %s/index.html 302\n' "$PREFIX" >&"$fd"
  printf '\treverse_proxy %s {\n' "$UPSTREAM" >&"$fd"
  printf '\t\theader_up X-Forwarded-Proto {scheme}\n' >&"$fd"
  printf '\t\theader_up X-Forwarded-For {remote_host}\n' >&"$fd"
  printf '\t\theader_up X-Forwarded-Host {host}\n' >&"$fd"
  printf '\t}\n' >&"$fd"
}

if [[ "$TLS_ENABLE" == "1" || "$TLS_ENABLE" == "true" || "$TLS_ENABLE" == "yes" ]]; then
  if [[ ! -f "$TLS_CERT" || ! -f "$TLS_KEY" ]]; then
    echo "TLS enabled but cert or key missing: $TLS_CERT $TLS_KEY" >&2
    exit 1
  fi
  exec {out}>"$OUT_FILE"
  printf '# BAS Lite reverse proxy (HTTP→HTTPS) — generated by render-caddyfile.sh\n\n' >&"$out"
  printf ':80 {\n\tredir https://{host}{uri} permanent\n}\n\n' >&"$out"
  printf ':443 {\n' >&"$out"
  printf '\ttls %s %s\n' "$TLS_CERT" "$TLS_KEY" >&"$out"
  write_common_block "$out"
  printf '}\n' >&"$out"
  exec {out}>&-
else
  exec {out}>"$OUT_FILE"
  printf '# BAS Lite reverse proxy (HTTP) — generated by render-caddyfile.sh\n\n' >&"$out"
  printf ':80 {\n' >&"$out"
  write_common_block "$out"
  printf '}\n' >&"$out"
  exec {out}>&-
fi

if getent passwd caddy >/dev/null 2>&1; then
  chown root:caddy "$OUT_FILE" 2>/dev/null || true
  chmod 0640 "$OUT_FILE" 2>/dev/null || true
fi

echo "Wrote $OUT_FILE"
