# Generated by Django 6.0.4 on 2026-04-30 19:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AuditLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ts", models.BigIntegerField()),
                ("username", models.CharField(max_length=255)),
                ("role", models.CharField(max_length=64)),
                ("action", models.CharField(max_length=255)),
                ("success", models.IntegerField(default=1)),
                ("details_json", models.TextField(default="{}")),
            ],
            options={
                "db_table": "audit_logs",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "bas_role",
                    models.CharField(
                        choices=[
                            ("system_integrator", "System integrator"),
                            ("maintenance", "Maintenance"),
                            ("building_operator", "Building operator"),
                        ],
                        default="building_operator",
                        max_length=64,
                    ),
                ),
                ("read_only", models.BooleanField(default=False)),
                ("must_change_password", models.BooleanField(default=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bas_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "bas_userprofile",
            },
        ),
    ]
